In [1]:
import pynq.lib.dma
import numpy as np
from pynq import Overlay

mmol = pynq.Overlay("./mul.bit")

mmol.hierarchy_dict


dma0 = mmol.axi_dma_0
dma1 = mmol.axi_dma_1


#hls_ip=mmol.matrixmul_0


from pynq import allocate

#矩阵缓冲区分配
a = allocate(shape=(32,32), dtype=np.int32)
b = allocate(shape=(32,32), dtype=np.int32)
res = allocate(shape=(32,32), dtype=np.int32)

a.device_address
b.device_address
res.device_address

for i in range(32):
    for j in range(32):
        a[i][j] = 6;
        b[i][j] = 8;
#刷新缓冲区以确保更新的数据对可编程数据可见 
a.flush()
b.flush()
res.flush()
#数据导入乘法器              
#dma0.sendchannel.transfer(a)
#dma1.sendchannel.transfer(b)
#dma0.recvchannel.transfer(res)
#hls_ip.write(0x00,0x01)

#print(a)
#print(b)
#print(res)

In [2]:
dma0.sendchannel.transfer(a)
dma1.sendchannel.transfer(b)
print(a)
print(b)

[[6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]
 ...
 [6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]]
[[8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]
 ...
 [8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]]


In [3]:
dma0.recvchannel.transfer(res)

print(res)

[[1536 1536 1536 ... 1536 1536 1536]
 [1536 1536 1536 ... 1536 1536 1536]
 [1536 1536 1536 ... 1536 1536 1536]
 ...
 [1536 1536 1536 ... 1536 1536 1536]
 [1536 1536 1536 ... 1536 1536 1536]
 [1536 1536 1536 ... 1536 1536 1536]]
